// Seed data for the admin backend demo. Loaded once on first mount if
// nothing exists in localStorage yet. Realistic enough for review, not
// tied to real people/companies.

import { addDays, addHours, format, subDays } from "date-fns";
import type {
  AdminState,
  Appointment,
  Availability,
  Customer,
  OutboundMessage,
  Prospect,
  Settings,
  Submission,
  Task,
  Transaction,
} from "./types";

const now = new Date("2026-05-15T14:00:00Z");
const iso = (d: Date) => d.toISOString();

const prospects: Prospect[] = [
  {
    id: "p_1",
    company: "Fort Wayne Metal Products",
    website: "https://fwmetal.example.com",
    industry: "Manufacturing",
    employeeCount: 68,
    location: "Fort Wayne, IN",
    stage: "to_contact",
    fitScore: 9,
    fitReason:
      "Self-funded manufacturer in Allen County. GLP-1 spend is likely a pain point. Owner is a Rotary member.",
    contacts: [
      {
        name: "Sarah Kettering",
        title: "HR Director",
        email: "sarah@fwmetal.example.com",
        phone: "260-555-0113",
      },
    ],
    activities: [
      {
        id: "a_1",
        type: "note",
        body: "Found via Indiana Manufacturers Assn. directory. Sarah confirmed HR ownership.",
        createdAt: iso(subDays(now, 2)),
      },
    ],
    ownerLabel: "researcher",
    tags: ["manufacturer", "self-funded"],
    estValueUsd: 68000,
    nextFollowUp: iso(addDays(now, 2)),
    createdAt: iso(subDays(now, 3)),
    updatedAt: iso(subDays(now, 2)),
  },
  {
    id: "p_2",
    company: "Northeast Indiana Logistics",
    website: "https://neilogistics.example.com",
    industry: "Trucking / Logistics",
    employeeCount: 42,
    location: "New Haven, IN",
    stage: "contacted",
    fitScore: 8,
    fitReason:
      "Fleet manager already looking for DOT physical partner. DPC + occ-med bundle would fit.",
    contacts: [
      {
        name: "Mike Delaney",
        title: "Fleet Manager",
        email: "mike@neilogistics.example.com",
        phone: "260-555-0187",
      },
    ],
    activities: [
      {
        id: "a_2",
        type: "email",
        body: "Sent intro email + DOT pricing sheet 2 days ago. No response yet.",
        createdAt: iso(subDays(now, 2)),
      },
    ],
    tags: ["logistics", "occ-med"],
    estValueUsd: 42000,
    nextFollowUp: iso(addDays(now, 1)),
    createdAt: iso(subDays(now, 6)),
    updatedAt: iso(subDays(now, 2)),
  },
  {
    id: "p_3",
    company: "Allen County Trades Group",
    industry: "HVAC / Plumbing / Electrical",
    employeeCount: 28,
    location: "Fort Wayne, IN",
    stage: "meeting_booked",
    fitScore: 8,
    fitReason: "Consortium of 4 trades shops. Sharing HR across the group.",
    contacts: [
      {
        name: "Dan Frisch",
        title: "Owner / Consortium Lead",
        email: "dan@actrades.example.com",
        phone: "260-555-0142",
      },
    ],
    activities: [
      {
        id: "a_3",
        type: "meeting",
        body: "Zoom booked for next Tuesday 10 AM. Bringing pricing sheet + Aluri bio.",
        createdAt: iso(subDays(now, 1)),
      },
    ],
    tags: ["trades", "consortium"],
    estValueUsd: 32000,
    nextFollowUp: iso(addDays(now, 4)),
    createdAt: iso(subDays(now, 10)),
    updatedAt: iso(subDays(now, 1)),
  },
  {
    id: "p_4",
    company: "Sweetwater Sound",
    website: "https://sweetwater.com",
    industry: "E-commerce / Music Retail",
    employeeCount: 1200,
    location: "Fort Wayne, IN",
    stage: "researched",
    fitScore: 6,
    fitReason:
      "Large employer — may already have self-funded plan. Long shot but a marquee win.",
    contacts: [],
    activities: [],
    tags: ["long-shot", "enterprise"],
    createdAt: iso(subDays(now, 1)),
    updatedAt: iso(subDays(now, 1)),
  },
  {
    id: "p_5",
    company: "Regal Ware Distributing",
    industry: "Wholesale Distribution",
    employeeCount: 22,
    location: "Fort Wayne, IN",
    stage: "won",
    fitScore: 10,
    fitReason: "First employer client. Signed for 22 employees at $79 PEPM.",
    contacts: [
      {
        name: "Ellen Riehle",
        title: "Operations Manager",
        email: "ellen@regalware.example.com",
      },
    ],
    activities: [
      {
        id: "a_4",
        type: "note",
        body: "Contract signed. 22 employees enrolled. Start date 6/1.",
        createdAt: iso(subDays(now, 8)),
      },
    ],
    tags: ["signed"],
    estValueUsd: 20856,
    createdAt: iso(subDays(now, 30)),
    updatedAt: iso(subDays(now, 8)),
  },
];

const submissions: Submission[] = [
  {
    id: "s_1",
    type: "contact",
    name: "Marcus Reilly",
    email: "marcus.r@example.com",
    phone: "260-555-0198",
    message:
      "Interested in learning more about a family membership for me, my wife, and 2 kids. What are next steps?",
    read: false,
    archived: false,
    createdAt: iso(subDays(now, 0)),
  },
  {
    id: "s_2",
    type: "patient",
    name: "Jessica Hood",
    email: "jhood@example.com",
    phone: "260-555-0164",
    subject: "New patient intake completed",
    meta: { formVersion: "v1", pages: 5 },
    read: false,
    archived: false,
    createdAt: iso(subDays(now, 1)),
  },
  {
    id: "s_3",
    type: "employer",
    name: "Ben Patel — Patel Precision Machining",
    email: "ben@patelprecision.example.com",
    phone: "260-555-0122",
    subject: "34 employees, self-funded, wanting a call",
    message:
      "We're currently on a fully-insured plan through UnitedHealthcare and looking for options. Please call to discuss.",
    read: true,
    archived: false,
    createdAt: iso(subDays(now, 3)),
  },
  {
    id: "s_4",
    type: "contact",
    name: "Angela Weaver",
    email: "angela.w@example.com",
    message: "Just curious about the Weight Loss program. Do you take HSA?",
    read: true,
    archived: false,
    createdAt: iso(subDays(now, 4)),
  },
];

const customers: Customer[] = [
  {
    id: "c_1",
    firstName: "Marcus",
    lastName: "Reilly",
    email: "marcus.r@example.com",
    phone: "260-555-0198",
    dob: "1978-04-12",
    membership: "family",
    membershipStart: iso(subDays(now, 42)),
    notes: [],
    createdAt: iso(subDays(now, 42)),
  },
  {
    id: "c_2",
    firstName: "Jessica",
    lastName: "Hood",
    email: "jhood@example.com",
    phone: "260-555-0164",
    dob: "1985-09-22",
    membership: "standard",
    membershipStart: iso(subDays(now, 15)),
    notes: [
      {
        id: "n_1",
        body: "New patient — first visit went well. Referred by Angela Weaver.",
        authorLabel: "Dr. Aluri",
        createdAt: iso(subDays(now, 14)),
      },
    ],
    createdAt: iso(subDays(now, 15)),
  },
  {
    id: "c_3",
    firstName: "Angela",
    lastName: "Weaver",
    email: "angela.w@example.com",
    phone: "260-555-0155",
    dob: "1990-01-05",
    membership: "platinum",
    membershipStart: iso(subDays(now, 120)),
    notes: [],
    createdAt: iso(subDays(now, 120)),
  },
  {
    id: "c_4",
    firstName: "Derek",
    lastName: "Yoder",
    email: "derek.y@example.com",
    phone: "260-555-0171",
    dob: "1966-11-30",
    membership: "employer",
    membershipStart: iso(subDays(now, 8)),
    employerId: "p_5",
    notes: [],
    createdAt: iso(subDays(now, 8)),
  },
];

const appointments: Appointment[] = [
  {
    id: "ap_1",
    customerId: "c_1",
    customerName: "Marcus Reilly",
    type: "annual_wellness",
    status: "scheduled",
    startsAt: iso(addHours(now, 3)),
    endsAt: iso(addHours(now, 4)),
    location: "in_office",
    requiresIntake: false,
    createdAt: iso(subDays(now, 5)),
  },
  {
    id: "ap_2",
    customerId: "c_2",
    customerName: "Jessica Hood",
    type: "follow_up",
    status: "scheduled",
    startsAt: iso(addDays(now, 1)),
    endsAt: iso(addHours(addDays(now, 1), 0.75)),
    location: "in_office",
    requiresIntake: false,
    createdAt: iso(subDays(now, 3)),
  },
  {
    id: "ap_3",
    customerName: "Fort Wayne Metal — Sarah K.",
    type: "business_meeting",
    status: "scheduled",
    startsAt: iso(addDays(now, 2)),
    endsAt: iso(addHours(addDays(now, 2), 1)),
    location: "virtual",
    notes: "Discussing 68-employee PEPM contract",
    requiresIntake: false,
    createdAt: iso(subDays(now, 1)),
  },
  {
    id: "ap_4",
    customerId: "c_3",
    customerName: "Angela Weaver",
    type: "weight_loss",
    status: "scheduled",
    startsAt: iso(addDays(now, 3)),
    endsAt: iso(addHours(addDays(now, 3), 0.75)),
    location: "in_office",
    requiresIntake: false,
    createdAt: iso(subDays(now, 7)),
  },
  {
    id: "ap_5",
    customerName: "James Peterson (new)",
    type: "new_patient",
    status: "scheduled",
    startsAt: iso(addDays(now, 4)),
    endsAt: iso(addHours(addDays(now, 4), 1)),
    location: "in_office",
    requiresIntake: true,
    createdAt: iso(subDays(now, 1)),
  },
  {
    id: "ap_6",
    customerId: "c_4",
    customerName: "Derek Yoder",
    type: "annual_wellness",
    status: "completed",
    startsAt: iso(subDays(now, 3)),
    endsAt: iso(addHours(subDays(now, 3), 1)),
    location: "in_office",
    requiresIntake: false,
    createdAt: iso(subDays(now, 10)),
  },
];

const transactions: Transaction[] = [
  {
    id: "t_1",
    customerId: "c_1",
    customerName: "Marcus Reilly",
    kind: "membership",
    amount: 20000,
    currency: "USD",
    description: "Family plan — May 2026",
    occurredAt: iso(subDays(now, 1)),
  },
  {
    id: "t_2",
    customerId: "c_3",
    customerName: "Angela Weaver",
    kind: "membership",
    amount: 25000,
    currency: "USD",
    description: "Platinum plan — May 2026",
    occurredAt: iso(subDays(now, 3)),
  },
  {
    id: "t_3",
    customerName: "Regal Ware Distributing",
    kind: "employer_contract",
    amount: 173800,
    currency: "USD",
    description: "22 employees × $79 PEPM — June 2026",
    occurredAt: iso(subDays(now, 5)),
  },
  {
    id: "t_4",
    customerId: "c_2",
    customerName: "Jessica Hood",
    kind: "membership",
    amount: 7900,
    currency: "USD",
    description: "Standard plan — May 2026 (age 40-49)",
    occurredAt: iso(subDays(now, 7)),
  },
  {
    id: "t_5",
    customerName: "Kim Rutherford",
    kind: "aesthetics",
    amount: 27000,
    currency: "USD",
    description: "30 units Botox (Mother's Day promo)",
    occurredAt: iso(subDays(now, 2)),
  },
  {
    id: "t_6",
    customerName: "NE Indiana Trucking Co.",
    kind: "occupational",
    amount: 62500,
    currency: "USD",
    description: "5 DOT physicals × $125",
    occurredAt: iso(subDays(now, 4)),
  },
];

const tasks: Task[] = [
  {
    id: "tk_1",
    title: "Follow up with Sarah at FW Metal",
    detail: "She said Friday call. Confirm employee count before pitch.",
    priority: "high",
    done: false,
    linkedProspectId: "p_1",
    dueAt: iso(addDays(now, 2)),
    createdAt: iso(subDays(now, 1)),
  },
  {
    id: "tk_2",
    title: "Prep 22-employee onboarding for Regal Ware",
    detail: "Enrollment forms, welcome packet, first-visit slots blocked",
    priority: "high",
    done: false,
    linkedProspectId: "p_5",
    dueAt: iso(addDays(now, 3)),
    createdAt: iso(subDays(now, 2)),
  },
  {
    id: "tk_3",
    title: "Renew NRCME for DOT physicals",
    priority: "medium",
    done: false,
    dueAt: iso(addDays(now, 30)),
    createdAt: iso(subDays(now, 5)),
  },
  {
    id: "tk_4",
    title: "Send May transactions report to Aluri",
    priority: "low",
    done: true,
    createdAt: iso(subDays(now, 8)),
  },
];

const availability: Availability = {
  weekly: [
    { weekday: 0, enabled: false, open: "10:00", close: "16:00" },
    { weekday: 1, enabled: true, open: "10:00", close: "17:00" },
    { weekday: 2, enabled: true, open: "09:00", close: "17:00" },
    { weekday: 3, enabled: true, open: "10:00", close: "17:00" },
    { weekday: 4, enabled: true, open: "09:00", close: "17:00" },
    { weekday: 5, enabled: true, open: "10:00", close: "17:00" },
    { weekday: 6, enabled: false, open: "10:00", close: "14:00" },
  ],
  blocks: [
    {
      id: "b_1",
      date: format(addDays(now, 12), "yyyy-MM-dd"),
      reason: "CME conference",
    },
  ],
  bufferMinutes: 15,
  virtualEnabled: true,
};

const settings: Settings = {
  practiceName: "Fort Wayne Direct Primary Care",
  contactEmail: "info@fortwaynedpc.com",
  contactPhone: "260-547-7543",
  address: "4630 W Jefferson Blvd, Suite 8, Fort Wayne, IN 46804",
  emailNotifications: true,
  smsNotifications: false,
  brandColor: "#2b6cb0",
};

const messages: OutboundMessage[] = [
  {
    id: "m_1",
    channel: "email",
    to: "sarah@fwmetal.example.com",
    toName: "Sarah Kettering",
    subject: "Direct primary care for your team — quick call?",
    body: "Hi Sarah — following up on our note about direct primary care for FW Metal's 68 employees. Would love 20 minutes this week to walk through pricing.",
    status: "sent",
    createdAt: iso(subDays(now, 2)),
    sentAt: iso(subDays(now, 2)),
  },
  {
    id: "m_2",
    channel: "sms",
    to: "260-555-0122",
    toName: "Ben Patel",
    body: "Hi Ben — Dr. Aluri here. Following up on your web form. When works for a quick call?",
    status: "draft",
    createdAt: iso(subDays(now, 0)),
  },
];

export const SEED: AdminState = {
  prospects,
  submissions,
  appointments,
  customers,
  transactions,
  tasks,
  availability,
  settings,
  messages,
};
